<a href="https://colab.research.google.com/github/Lukehsu1999/Academic-and-Formality-Rewriter/blob/main/evaluation/Manual_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sentences

In [ ]:
set_path = "EM_test"
test_code = "EM"
test_full_name = "Entertainment_Music"  #"Entertainment_Music" "Family_Relationships"

Get Model Output

In [ ]:
path_to_EMFRmodel_output = "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/EMFR_model_3pochs_"+test_code+"_test"
EMFRmodel_output_file = open(path_to_EMFRmodel_output, "r")
EMFRmodel_output_lines = EMFRmodel_output_file.readlines()

path_to_EMmodel_output = "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/EM_model_3pochs_"+test_code+"_test"
EMmodel_output_file = open(path_to_EMmodel_output, "r")
EMmodel_output_lines = EMmodel_output_file.readlines()

path_to_FRmodel_output = "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/FR_model_3pochs_"+test_code+"_test"
FRmodel_output_file = open(path_to_FRmodel_output, "r")
FRmodel_output_lines = FRmodel_output_file.readlines()

path_to_nmtbaselinemodel_output = "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/formal.nmt_baseline"
nmtbaselinemodel_output_file = open(path_to_nmtbaselinemodel_output, "r")
nmtbaselinemodel_output_lines = nmtbaselinemodel_output_file.readlines()

path_to_nmtcombinedmodel_output = "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/formal.nmt_combined"
nmtcombinedmodel_output_file = open(path_to_nmtcombinedmodel_output, "r")
nmtcombinedmodel_output_lines = nmtcombinedmodel_output_file.readlines()

path_to_nmtcopymodel_output = "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/formal.nmt_copy"
nmtcopymodel_output_file = open(path_to_nmtcopymodel_output, "r")
nmtcopymodel_output_lines = nmtcopymodel_output_file.readlines()

path_to_pbmtmodel_output = "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/formal.pbmt"
pbmtmodel_output_file = open(path_to_pbmtmodel_output, "r")
pbmtmodel_output_lines = pbmtmodel_output_file.readlines()

path_to_rulebasedmodel_output = "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/formal.rule_based"
rulebasedmodel_output_file = open(path_to_rulebasedmodel_output, "r")
rulebasedmodel_output_lines = rulebasedmodel_output_file.readlines()

In [ ]:
print(len(EMFRmodel_output_lines))

1416


In [ ]:
all_set = {
    "EMFR":EMFRmodel_output_lines,
    "EM":EMmodel_output_lines,
    "FR":FRmodel_output_lines,
    "nmtbaseline":nmtbaselinemodel_output_lines,
    "nmtcombined":nmtcombinedmodel_output_lines,
    "nmtcopy":nmtcopymodel_output_lines,
    "pbmt":pbmtmodel_output_lines,
    "rulebased":rulebasedmodel_output_lines
}

Get Model Input

In [ ]:
path_to_model_input = "/content/drive/MyDrive/CityU/FYP/Datasets/GYAFC/GYAFC_Corpus/"+test_full_name+"/test/informal"
model_input_file = open(path_to_model_input, "r")
model_input_lines = model_input_file.readlines()
print(len(model_input_lines))

1416


In [ ]:
all_set["input"] = model_input_lines

In [ ]:
print(all_set.keys())

dict_keys(['EMFR', 'EM', 'FR', 'nmtbaseline', 'nmtcombined', 'nmtcopy', 'pbmt', 'rulebased', 'input'])


Get reference sentences

In [ ]:
path_to_references = ["/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/references/formal.ref0",
            "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/references/formal.ref1",
            "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/references/formal.ref2",
            "/content/drive/MyDrive/CityU/FYP/Model_Outputs/"+set_path+"/references/formal.ref3"]
reference_lines = []
for i in range(len(path_to_references)):
  temp_ref_file = open(path_to_references[i], "r")
  temp_ref_lines = temp_ref_file.readlines()
  temp_lines = []
  for line in temp_ref_lines:
    temp_lines.append(line)
  reference_lines.append(temp_lines)

print(len(reference_lines))
print(len(reference_lines[0]))

4
1416


In [ ]:
all_set["ref0"] = reference_lines[0]
all_set["ref1"] = reference_lines[1]
all_set["ref2"] = reference_lines[2]
all_set["ref3"] = reference_lines[3]

In [ ]:
for key in all_set.keys():
  print(key)
  print(len(all_set[key]))

# Evaluations

Get Formality Classification Results

In [ ]:
path_to_FCresult_dict = "/content/drive/MyDrive/CityU/FYP/Evaluation/Classification_Results/Formal_Classification/"+test_code+"_results.json"

# josn load
import json
with open(path_to_FCresult_dict, 'r') as fcfp:
    FC_result_dict = json.load(fcfp)

print(FC_result_dict.keys())

dict_keys(['EMFR', 'EM', 'FR', 'nmtbaseline', 'nmtcombined', 'nmtcopy', 'pbmt', 'rulebased', 'ref0', 'ref1', 'ref2', 'ref3'])


In [ ]:
print(FC_result_dict["EMFR"][0:20])

['tf.Tensor([[0.69081926 0.3091807 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[2.3516946e-04 9.9976486e-01]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.017417   0.98258305]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[3.0193877e-04 9.9969804e-01]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.00226283 0.99773717]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[8.5682265e-04 9.9914312e-01]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.11004686 0.8899532 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.00194388 0.9980562 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.742284   0.25771597]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.02950102 0.970499  ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.0190705 0.9809295]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.2783649 0.7216351]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[4.9357535e-04 9.9950647e-01]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[3.5575152e-04 9.9964428e-01]], shape=(1, 2), dtype=float32)', 'tf.Ten

Get Academic Classification Results

In [ ]:
path_to_ACresult_dict = "/content/drive/MyDrive/CityU/FYP/Evaluation/Classification_Results/Academic_Classification/"+test_code+"_results.json"

# josn load
import json
with open(path_to_ACresult_dict, 'r') as acfp:
    AC_result_dict = json.load(acfp)

print(AC_result_dict.keys())

dict_keys(['EMFR', 'EM', 'FR', 'nmtbaseline', 'nmtcombined', 'nmtcopy', 'pbmt', 'rulebased', 'ref0', 'ref1', 'ref2', 'ref3'])


In [ ]:
print(AC_result_dict["EMFR"][0:20])

['tf.Tensor([[0.38465795 0.6153421 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[1.4582198e-04 9.9985421e-01]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.06609886 0.93390113]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.00103276 0.9989673 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.00792496 0.9920751 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.00193212 0.9980679 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.26433358 0.73566645]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[9.7452092e-04 9.9902546e-01]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.8148307  0.18516932]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.01175569 0.9882443 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.00176565 0.9982343 ]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[0.09618385 0.90381616]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[8.840894e-04 9.991159e-01]], shape=(1, 2), dtype=float32)', 'tf.Tensor([[1.4691967e-04 9.9985301e-01]], shape=(1, 2), dtype=float32)', 'tf.Tensor(

Get Language Tool Python Results

In [ ]:
path_to_Grammar_Score = "/content/drive/MyDrive/CityU/FYP/Evaluation/Language_Tool_Python_Results/"+test_code+"_Grammar_Score_dict.json"
path_to_Grammar_Match = "/content/drive/MyDrive/CityU/FYP/Evaluation/Language_Tool_Python_Results/"+test_code+"_Grammar_Match_dict.json"

with open(path_to_Grammar_Score, 'r') as gsfp:
  Grammar_score_dict = json.load(gsfp)
with open(path_to_Grammar_Match, 'r') as gmfp:
  Grammar_match_dict = json.load(gmfp)

In [ ]:
print(Grammar_score_dict.keys())
print(Grammar_score_dict["EMFR"][0:20])

dict_keys(['EMFR', 'EM', 'FR', 'nmtbaseline', 'nmtcombined', 'nmtcopy', 'pbmt', 'rulebased', 'ref0', 'ref1', 'ref2', 'ref3'])
[1.0, 0.8421052631578947, 1.0, 1.0, 0.9523809523809523, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9285714285714286, 1.0, 1.0, 1.0]


In [ ]:
print(Grammar_match_dict.keys())
print(Grammar_match_dict["EMFR"][0:20])

dict_keys(['EMFR', 'EM', 'FR', 'nmtbaseline', 'nmtcombined', 'nmtcopy', 'pbmt', 'rulebased', 'ref0', 'ref1', 'ref2', 'ref3'])
['[]', "[Match({'ruleId': 'MORFOLOGIK_RULE_EN_US', 'message': 'Possible spelling mistake found.', 'replacements': ['Aspen ado'], 'offsetInContext': 0, 'context': 'Aspenado colora has the best music festivals, yo...', 'offset': 0, 'errorLength': 8, 'category': 'TYPOS', 'ruleIssueType': 'misspelling', 'sentence': 'Aspenado colora has the best music festivals, you will be able to spend time on the moutians.'}), Match({'ruleId': 'MORFOLOGIK_RULE_EN_US', 'message': 'Possible spelling mistake found.', 'replacements': ['color', 'colors', 'color a', 'Coloma'], 'offsetInContext': 9, 'context': 'Aspenado colora has the best music festivals, you will ...', 'offset': 9, 'errorLength': 6, 'category': 'TYPOS', 'ruleIssueType': 'misspelling', 'sentence': 'Aspenado colora has the best music festivals, you will be able to spend time on the moutians.'}), Match({'ruleId': 'MORFOLO

# Review results:

In [ ]:
def get_certainty_from_tf_string(tf_string):
  inner_left_bracket_id = tf_string.index(']')
  inner_right_bracket = tf_string.index('[')+1
  inner = tf_string[inner_right_bracket+1:inner_left_bracket_id]
  #print(inner)
  inner_tokens = inner.split()
  #print(inner_tokens)
  return inner_tokens[1]

In [ ]:
def print_idx(id):
  print("Input: ")
  print("Sentence: "+all_set['input'][id])
  for k in all_set.keys():
    if k == "input":
      continue
    else:
      print("Model: "+str(k))
      print("Sentence: "+all_set[k][id])
      formal_score = float(get_certainty_from_tf_string(FC_result_dict[k][id]))
      academic_score = float(get_certainty_from_tf_string(AC_result_dict[k][id]))
      print("Formality Classification Score: "+get_certainty_from_tf_string(FC_result_dict[k][id]))
      print("Academic Classification Score: "+get_certainty_from_tf_string(AC_result_dict[k][id]))
      print("Academic Classification Score: "+AC_result_dict[k][id])
      print("Grammar Score: "+str(Grammar_score_dict[k][id]))
      print()

In [ ]:
print_idx(96)

# Filter

In [ ]:
def get_score(input):
  if isinstance(input, str): # for Formality Classification, Academic Classification
    return float(get_certainty_from_tf_string(input))
  else: # for Grammar Score
    return input

In [ ]:
def filter_by(score_dict, threshold):
  n = len(score_dict["EMFR"])
  res_lst = []
  for i in range(n):
    avg_transformer_score = 0 #EMFR, EM, FR
    avg_model_score = 0  # nmt-family, pbmt
    avg_reference_score = 0

    avg_transformer_score += get_score(score_dict["EMFR"][i])
    avg_transformer_score += get_score(score_dict["EM"][i])
    avg_transformer_score += get_score(score_dict["FR"][i])
    avg_transformer_score /= 3

    # 'nmtbaseline', 'nmtcombined', 'nmtcopy', 'pbmt'
    avg_model_score += get_score(score_dict["nmtbaseline"][i])
    avg_model_score += get_score(score_dict["nmtcombined"][i])
    avg_model_score += get_score(score_dict["nmtcopy"][i])
    avg_model_score += get_score(score_dict["pbmt"][i])
    avg_model_score /= 4

    if avg_transformer_score - avg_model_score >= threshold:
      res_lst.append(i)
  return res_lst
    

In [ ]:
FC_lst = filter_by(FC_result_dict, 0.25)
print(len(FC_lst))
print(FC_lst)

267
[11, 18, 20, 27, 32, 36, 39, 42, 43, 44, 46, 55, 65, 81, 83, 87, 93, 94, 112, 118, 121, 124, 126, 128, 132, 137, 145, 149, 163, 166, 167, 170, 172, 178, 185, 186, 189, 190, 194, 198, 203, 209, 212, 216, 218, 219, 223, 231, 233, 241, 244, 257, 258, 259, 263, 264, 275, 276, 277, 278, 279, 280, 284, 286, 290, 291, 294, 296, 304, 306, 307, 309, 310, 329, 331, 333, 343, 350, 355, 363, 366, 367, 398, 400, 427, 430, 436, 437, 438, 440, 453, 456, 462, 472, 474, 486, 488, 489, 494, 500, 511, 515, 517, 518, 524, 526, 529, 533, 540, 543, 544, 549, 554, 557, 561, 577, 579, 581, 593, 601, 603, 610, 611, 614, 616, 617, 625, 628, 630, 633, 637, 639, 644, 646, 650, 653, 654, 655, 659, 660, 662, 678, 704, 705, 708, 711, 712, 717, 718, 720, 750, 765, 782, 799, 820, 821, 834, 842, 844, 846, 847, 852, 853, 855, 862, 864, 884, 886, 891, 892, 907, 910, 912, 923, 934, 939, 949, 958, 962, 963, 969, 971, 977, 981, 988, 991, 995, 1003, 1004, 1005, 1016, 1019, 1022, 1027, 1030, 1050, 1060, 1064, 1068, 1072, 

In [ ]:
AC_lst = filter_by(AC_result_dict, 0.25)
print(len(AC_lst))
print(AC_lst)

443
[0, 1, 11, 13, 14, 18, 19, 20, 26, 27, 32, 37, 39, 42, 43, 44, 46, 55, 57, 61, 72, 83, 85, 87, 90, 92, 93, 107, 112, 114, 116, 118, 121, 123, 124, 126, 128, 131, 135, 137, 139, 142, 145, 146, 148, 149, 154, 157, 160, 162, 163, 166, 167, 168, 169, 170, 172, 178, 181, 182, 185, 189, 190, 191, 192, 194, 198, 199, 200, 203, 204, 206, 208, 209, 212, 216, 218, 219, 223, 224, 227, 231, 233, 239, 240, 241, 250, 255, 257, 258, 263, 264, 267, 268, 271, 273, 275, 277, 280, 282, 284, 286, 290, 291, 292, 294, 296, 304, 306, 307, 310, 319, 322, 331, 332, 333, 337, 341, 343, 350, 358, 359, 362, 363, 366, 367, 370, 371, 372, 376, 377, 378, 387, 400, 408, 411, 414, 420, 423, 427, 428, 430, 432, 435, 436, 437, 438, 440, 447, 448, 453, 458, 459, 460, 462, 467, 472, 474, 476, 479, 488, 494, 500, 504, 511, 515, 517, 518, 519, 526, 529, 540, 541, 543, 544, 546, 549, 554, 557, 561, 565, 570, 574, 579, 581, 588, 591, 593, 600, 604, 606, 609, 610, 611, 613, 614, 616, 617, 620, 621, 622, 623, 625, 626, 628,

In [ ]:
Grammar_lst = filter_by(Grammar_score_dict, 0.25)
print(len(Grammar_lst))
print(Grammar_lst)

67
[28, 43, 58, 64, 111, 121, 142, 156, 163, 228, 259, 290, 295, 305, 327, 367, 421, 424, 428, 438, 507, 527, 530, 551, 552, 559, 572, 578, 583, 609, 617, 686, 688, 702, 709, 753, 758, 762, 848, 873, 945, 964, 985, 991, 999, 1003, 1035, 1060, 1063, 1091, 1107, 1120, 1127, 1170, 1208, 1217, 1224, 1246, 1247, 1282, 1288, 1303, 1312, 1320, 1322, 1355, 1370]


In [ ]:
def intersection(lists):
  ans_lst = lists[0]
  for i in range(1,len(lists)):
    ans_lst = list(set(lists[i]) & set(ans_lst))
  return ans_lst

In [ ]:
overlap_lst = intersection([FC_lst, AC_lst, Grammar_lst])

In [ ]:
print(overlap_lst)

[290, 163, 1060, 1091, 1224, 617, 43, 1003, 367, 438, 1303, 121, 991]


In [ ]:
print_idx(991)